# Imagen base
FROM python:3.12-slim

# Evitar archivos .pyc y forzar salida inmediata de logs
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

# Establecer directorio de trabajo
WORKDIR /app

# Copiar dependencias
COPY requirements.txt .

# Instalar dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el resto del proyecto
COPY . .

# Dar permisos de ejecución al entrypoint
RUN chmod +x /app/entrypoint.sh

# Exponer el puerto de Flask
EXPOSE 5051

# Variables de entorno
ENV DB_PATH=/data/app.db \
    FLASK_RUN_PORT=5051

# Comando por defecto
CMD ["/app/entrypoint.sh"]